### ISSUE TITLE
jogo em um mundo ideal 

### ISSUE THREAD

**Issue by AnaPflegerkremerr** [The-New-Hera/On-The-Run#2]

**Comment by carstesss** [comment]
O jogo ideal seria de realidade virtual, ou seja, os jogadores se movimentariam para comandar as ações dos personagens. Além disso, haveria guardas perseguindo os alienígenas, tentando impedi-los de escapar, e os extraterrestres teriam que enfrentar mais obstáculos pelo caminho, como outras armadilhas e substâncias tóxicas. Se houvesse mais tempo disponível, poderíamos desenvolver um mapa com mais fases.
