### ISSUE TITLE
Descrever as regras do jogo

### ISSUE THREAD

**Issue by AnaPflegerkremerr** [The-New-Hera/On-The-Run#6]

**Comment by carstesss** [comment]
Os alienígenas enfrentarão obstáculos ao longo do caminho e precisarão um do outro, portanto ambos os personagens devem receber comandos do jogador. Nas primeiras fases, o objetivo é que ambos cheguem até as portas localizadas no fim do caminho. Na última fase, o objetivo é chegar à nave espacial que os levará de volta para o seu planeta. Eles não podem entrar em contato com as substâncias tóxicas, então devem evitá-las e, caso necessário, desativar possíveis armadilhas para poderem seguir em frente.
